### ISSUE TITLE
Semantic HTML

### ISSUE THREAD

**Issue by aubreywullschleger** [GinnyCobbett/tea-cosy#1]
Great! Nice job using semantic HTML elements like `<header>`, `<nav>`, `<main>` and `<footer>`.  Using semantic elements helps improve the accessibility of your page. Here's info on how semantic elements help with accessibility: https://webflow.com/blog/html5-semantic-elements-and-webflow-the-essential-guide (scroll down to the 'So what are semantic elements good for?' heading) and a list of more semantic elements you can use: http://www.techstrikers.com/HTML5/html5-semantic-elements.php

Example: https://github.com/GinnyCobbett/tea-cosy/blob/master/index.html#L25-L75

**Comment by GinnyCobbett** [comment]
Thanks! I prefer this as a way to order my html too, and sometimes its feels easier to control by css for divs and not semantic elements so much
