### ISSUE TITLE
Using locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [GinnyCobbett/tea-cosy#2]
Great! Awesome work using locally stored images for your project! This is best practice for production code and helps your page load faster. 

Example: https://github.com/GinnyCobbett/tea-cosy/blob/master/index.html#L14

Also, great job using descriptive `alt` attributes on your `<img>` elements! This is best practice as well and helps make your site more accessible.

One thing to work on with these is to make sure you are avoiding the use of inline-styles and making your HTML and CSS as modular as possible by keeping your styles in CSS. Line 14 you have `height="50px"` I would delete this attribute and use this in your CSS instead:
```
.logo img {
  height: 50px;
}
```

**Comment by GinnyCobbett** [comment]
Awesome! thanks and I've fixed that now :)
