### ISSUE TITLE
Flex-box in CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [GinnyCobbett/tea-cosy#4]
Great! Great job with your CSS. I love that you challenged yourself by using flex-box for your layout. I would consider adding group selectors for any repeated styles like `display: flex;` to make your CSS more concise.  I would also delete any unused selectors.

https://github.com/GinnyCobbett/tea-cosy/blob/master/resources/css/style.css#L57-L59

**Comment by GinnyCobbett** [comment]
Great, thanks I've done that now.
